apiVersion: spark.apache.org/v1
kind: SparkApplication
metadata:
  name: crypto-streaming-10m
  namespace: crypto-infra
  labels:
    app: crypto-streaming
    env: minikube
spec:
  mainApplicationFile: "local:///opt/spark/work-dir/spark_streaming_10m.py"
  
  sparkConf:
    spark.jars.packages: "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0"
    
    spark.dynamicAllocation.enabled: "true"
    spark.dynamicAllocation.shuffleTracking.enabled: "true"
    spark.dynamicAllocation.minExecutors: "1"
    spark.dynamicAllocation.maxExecutors: "2"
    spark.dynamicAllocation.initialExecutors: "1"
    
    spark.kubernetes.authenticate.driver.serviceAccountName: "spark"
    spark.kubernetes.container.image: "apache/spark:3.5.0"
    
    spark.driver.cores: "1"
    spark.driver.memory: "1g"
    
    spark.executor.cores: "1"
    spark.executor.memory: "1g"
    
    spark.eventLog.enabled: "false"
    
    spark.streaming.stopGracefullyOnShutdown: "true"
    spark.sql.streaming.schemaInference: "true"
    
    spark.sql.shuffle.partitions: "4"
    spark.default.parallelism: "4"
    
    spark.kubernetes.driverEnv.KAFKA_BOOTSTRAP_SERVERS: "my-cluster-kafka-bootstrap.crypto-infra.svc.cluster.local:9092"
    spark.kubernetes.driverEnv.KAFKA_TOPIC: "crypto_kline_1m"
    spark.executorEnv.KAFKA_BOOTSTRAP_SERVERS: "my-cluster-kafka-bootstrap.crypto-infra.svc.cluster.local:9092"
  
  applicationTolerations:
    resourceRetainPolicy: OnFailure
    restartConfig:
      restartPolicy: OnFailure
      maxRestartAttempts: 2
      restartBackoffMillis: 10000
  
  runtimeVersions:
    scalaVersion: "2.12"
    sparkVersion: "3.5.0"

