apiVersion: spark.apache.org/v1
kind: SparkApplication
metadata:
  name: spark-pi-test
  namespace: crypto-infra
  labels:
    app: spark-test
spec:
  mainClass: "org.apache.spark.examples.SparkPi"
  jars: "local:///opt/spark/examples/jars/spark-examples.jar"
  
  sparkConf:
    spark.dynamicAllocation.enabled: "true"
    spark.dynamicAllocation.shuffleTracking.enabled: "true"
    spark.dynamicAllocation.minExecutors: "1"
    spark.dynamicAllocation.maxExecutors: "2"
    spark.dynamicAllocation.initialExecutors: "1"
    
    spark.kubernetes.authenticate.driver.serviceAccountName: "spark"
    spark.kubernetes.container.image: "apache/spark:3.5.0"
    
    spark.driver.cores: "1"
    spark.driver.memory: "512m"
    
    spark.executor.cores: "1"
    spark.executor.memory: "512m"
  
  applicationTolerations:
    resourceRetainPolicy: Never
  
  runtimeVersions:
    scalaVersion: "2.12"
    sparkVersion: "3.5.0"

