apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: crypto-kline-1m
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    cleanup.policy: delete
